title: Change the humidity reading on a SenseHAT
hero_image: images/banner.png
description: Change the humidity reading on a SenseHAT
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - title: Change the humidity reading on a SenseHAT
